export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_PROMISE = 'SET_USER_PROMISE';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SET_WAITING_MEETINGS = 'SET_WAITING_MEETINGS';
export const SET_SELECTED_MEETING = 'SET_SELECTED_MEETING';
export const SET_CURRENT_MEETING = 'SET_CURRENT_MEETING';
export const RESET_MEETING = 'RESET_MEETING';
export const RESET_USER_INFO = 'RESET_USER_INFO';
