export default MESSAGE = {
  OK: 'ok',
  NO: 'NO',
  YES: 'YES',
  TIME_OUT_TITLE: '시간 종료',
  TIME_OUT: '약속이 취소되었습니다',
  CANCEL_TITLE: '약속 취소',
  CANCEL_MESSAGE: '상대방에 의해 약속이 취소되었습니다.',
  LOGOUT: '로그아웃하시겠습니까?',
  SHOULD_ENTER: '메세지를 입력해주세요',
  FIND_OTHER_RESTAURANT: '다른 맛집을 찾아볼까요?',
  IT_IS_CLOSED: '준비가 되지 않았습니다',
  SHOULD_INPUT_RESTAURANT: '맛집을 검색해주세요',
  SHOULD_ENTER_WORD: '검색어를 입력해주세요',
  CLOSE: 'close',
  OPEN: 'open',
  OBJECT: 'object',
  NO_MEMBER_EXISTED: 'no member information',
  ERROR_LOCATION_WAS_DENIED: 'Permission to access location was denied',
  STATUS_GRANTED: 'granted',
  COMPLATE_ARRIVAL: '도착 완료',
  CONFIRM_ARRIVAL: '도착 확인',
  CANCEL_PROMISE: '약속 취소하기',
  CONFIRM_CANCEL_PROMISE: '정말 취소하시겠습니까?',
  INVALID_LOGIN: '유효하지 않는 로그인입니다.',
  FAILED_LOGIN: '로그인에 실패했습니다.',
  UNKNWON_ERROR: '작업 도중 에러가 발생했습니다.',
};
