export default ROUTE = {
  HOME: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  SIGNUP: '/signup',
  USERS: '/users',
  USER_DETAIL: '/:userId',
  MEETINGS: '/meetings',
  MEETING_DETAIL: '/:meetingId',
  PREFERRED_PARTNER: '/preferred-partner',
  FAVORITE_PARTNERS: '/favorite-partners',
  CHAT: '/chat',
  JOIN: '/join',
  HISTORY: '/history',
  PROMISE: '/promise',
  PAYMENT: '/payment',
};
